<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>oracle-certificatons</artifactId>
    <groupId>br.com.oracle_certificatons.ocp</groupId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <groupId>br.com.oracle_certificatons.ocp.javase_25_developer</groupId>
  <artifactId>ocp-javase25-developer</artifactId>
  <packaging>pom</packaging>
  <name>ocp-javase25-developer</name>
  <modules>
    <module>data-type-manipulation</module>
    <module>flow-control</module>
    <module>object-oriented-principles</module>
    <module>exception-handling</module>
    <module>arrays-collections</module>
    <module>streams-lambda-expressions</module>
    <module>packaging-deployment</module>
    <module>concurrent-multithreading-execution</module>
    <module>io-api</module>
    <module>localization-support</module>
    <module>building-blocks</module>
    <module>operators</module>
    <module>making-decisions</module>
    <module>core-apis</module>
    <module>methods</module>
    <module>class-design</module>
    <module>beyond-classes</module>
    <module>lambdas-functional-interfaces</module>
    <module>collections-generics</module>
    <module>streams</module>
    <module>exceptions-localization</module>
    <module>modules</module>
    <module>concurrency</module>
  </modules>
</project>
